### ISSUE TITLE
您好，默认日期怎样设置呢？

### ISSUE THREAD

**Issue by hhzhi** [jamielhf/vue#11]
谢谢

**Comment by jamielhf** [comment]
现在这个组件有bug还没修复，所以暂时不建议使用，你可以用vux等ui组件

**Comment by 17316226495** [comment]
能不能推荐一款类似的，找了好久找不到

**Comment by hhzhi** [comment]
手机端  直接  input  type="date" 也行   
http://m.sui.taobao.org/components/#bars  （淘宝）
https://weui.io/(微信)

**Comment by jamielhf** [comment]
bug已经修复
