### ISSUE TITLE
请添加对startTime支持，谢谢

### ISSUE THREAD

**Issue by devtip** [jamielhf/vue#17]
项目中，可能有startTime这样的需求，尝试修改过你的项目代码，但还是没有成功。So sorry。（提示，对判断闰年（PS:isR逻辑，）与及计算当前月份的日期范围（PS:changeDataList部分逻辑）这样的功能函数分离到util模块，这样方便在startTime逻辑的编写，因为changeStartTime逻辑的编写很可能会用到）。。。。。。同样，isR判断闰年的逻辑似乎有点不太严谨。。。

**Comment by jamielhf** [comment]
最新版本已支持 startTime
