### ISSUE TITLE
年份样式偏移

### ISSUE THREAD

**Issue by rookierui** [jamielhf/vue#25]
![image](https://user-images.githubusercontent.com/25169019/38227982-79945d22-3733-11e8-93a3-d76cb01f9ccd.png)
z

**Comment by jamielhf** [comment]
请问是在pc浏览器还是在移动端的

**Comment by liwanbin** [comment]
在安卓手机上年份偏移，苹果手机正常

**Comment by jamielhf** [comment]
在最新的版本已经修复了
