### ISSUE TITLE
vue2-datepick版本2.1.0 初始化日历的问题

### ISSUE THREAD

**Issue by smallButVeryStrong** [jamielhf/vue#27]
引入该日历插件，点击按钮，显示日历组件。  #初始化的时候比如说6月份，会显示有31天。在modules/index.js里边添加处理，避免该问题
![image](https://user-images.githubusercontent.com/21958022/41957242-df55d7f8-7a18-11e8-99cf-c979dd9130a3.png)；

处理方式：
![image](https://user-images.githubusercontent.com/21958022/41963104-544997e2-7a29-11e8-8654-1d7048ee64e2.png)

希望可以处理

**Comment by jamielhf** [comment]
旧的版本可能有问题，建议用新的版本
