### ISSUE TITLE
麻烦问下，怎样给组建动态添加样式呢？

### ISSUE THREAD

**Issue by jingleding** [jamielhf/vue#37]
我现在在vue里面使用，一个页面有多个，但是日历组件的样式需要不一样，所以需要在组件的外层增加一个class，来对不同地方的日历组件添加不同的样式，有这样的配置项吗

**Comment by jamielhf** [comment]
目前没有配置项，只能通过提高权重覆盖之前的样式。

**Comment by jingleding** [comment]
哦，好吧
